# Generated by Django 3.2 on 2022-11-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_catalogwallfurniture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogHallway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(max_length=10, verbose_name='Цена')),
                ('content', models.TextField(verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Каталог - шкаф прихожая',
                'verbose_name_plural': 'Каталоги - шкафы прихожие',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogSofa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(max_length=10, verbose_name='Цена')),
                ('content', models.TextField(verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Каталог - диван',
                'verbose_name_plural': 'Каталоги - диваны',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(max_length=10, verbose_name='Цена')),
                ('content', models.TextField(verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Каталог - стол',
                'verbose_name_plural': 'Каталоги - столы',
                'ordering': ['-created_at'],
            },
        ),
    ]
