# Generated by Django 3.2 on 2022-11-29 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20221129_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
